# Generated by Django 3.0.4 on 2020-03-16 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(help_text='Member of team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='water.Team'),
        ),
    ]
